// src/components/Contact.tsx
import { Component } from "react";
import { ISocialMediaProfiles } from "../models/SocialMediaProfiles";
import { ADDRESS, EMAIL, PHONE } from "../util/constants";
import { loadScript } from "../util/helpers";

export class Contact extends Component<ISocialMediaProfiles> {
  componentDidMount() {
    loadScript("scripts/bootstrap.bundle.min.js?ver=1.2.0");
    loadScript("scripts/aos.js?ver=1.2.0");
    loadScript("scripts/main.js?ver=1.2.0");
  }

  render() {
    let emailUrl = `https://formspree.io/${EMAIL}`;

    return (
      <>
        <div className="contant-section px-3 px-lg-4 pb-4" id="contact">
          <h2 className="h3 text mb-3">Contact</h2>
          <div className="row">
            <div className="col-md-7 d-print-none">
              <div className="my-2">
                <form action={emailUrl} method="POST">
                  <div className="row">
                    <div className="col-6">
                      <input
                        className="form-control"
                        type="text"
                        id="name"
                        name="name"
                        placeholder="Your Name"
                        required
                      ></input>
                    </div>
                    <div className="col-6">
                      <input
                        className="form-control"
                        type="email"
                        id="email"
                        name="_replyto"
                        placeholder="Your E-mail"
                        required
                      ></input>
                    </div>
                  </div>
                  <div className="form-group my-2">
                    <textarea
                      className="form-control"
                      style={{ resize: "none" }}
                      id="message"
                      name="message"
                      rows={4}
                      placeholder="Your Message"
                      required
                    ></textarea>
                  </div>
                  <button className="btn btn-primary mt-2" type="submit">
                    Send
                  </button>
                </form>
              </div>
            </div>
            <div className="col">
              <div className="mt-2">
                <h3 className="h6">Address</h3>
                <div className="pb-2 text-secondary">{ADDRESS}</div>
                <h3 className="h6">Phone</h3>
                <div className="pb-2 text-secondary">{PHONE}</div>
                <h3 className="h6">Email</h3>
                <div className="pb-2 text-secondary">{EMAIL}</div>
              </div>
            </div>
            <div className="col d-none d-print-block">
              <div className="mt-2">
                <div>
                  {this.props.Profiles.map(
                    (profile) =>
                      profile.Url !== null && (
                        <>
                          <div className="mb-2">
                            <div className="text-dark">
                              <i className={profile.IconClass}></i>
                              <span className="ml-1">{profile.Url}</span>
                            </div>
                          </div>
                        </>
                      )
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  }
}

// src/app/content/contact/contact.component.ts
import { Component } from '@angular/core';
import { BaseComponent } from '@shared/base.component';
import { DataService } from '@services/data.service';
import { ContactModel } from '@shared/models/contact.model';

@Component({
    selector: 'app-contact',
    templateUrl: './contact.component.html'
})
export class ContactComponent extends BaseComponent {
    private _contact: ContactModel;

    constructor(private _dataService: DataService) {
        super();
    }

    ngOnInit(): void {
        this._contact = this._dataService.GetContact();
    }

    get Contact(): ContactModel {
        return this._contact;
    }
}
<agm-map class="cc-contact-information agm-map" [latitude]="26.887809" [longitude]="75.892514">
    <!-- style="background-image: url('assets/images/staticmap.png');" -->
    <div class="container">
        <div class="cc-contact">
            <div class="row">
                <div class="col-md-9">
                    <div class="card mb-0" data-aos="zoom-in">
                        <div class="h4 text-center title">Contact Me</div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card-body">
                                    <form action="https://formspree.io/{{Contact.FormsPreeEmail}}" method="POST">
                                        <div class="p pb-3"><strong>Feel free to contact me </strong></div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <div class="input-group"><span class="input-group-addon"><i
                                                            class="fa fa-user-circle"></i></span>
                                                    <input class="form-control" type="text" name="name"
                                                        placeholder="Name" required="required" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <div class="input-group"><span class="input-group-addon"><i
                                                            class="fa fa-file-text"></i></span>
                                                    <input class="form-control" type="text" name="Subject"
                                                        placeholder="Subject" required="required" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <div class="input-group"><span class="input-group-addon"><i
                                                            class="fa fa-envelope"></i></span>
                                                    <input class="form-control" type="email" name="_replyto"
                                                        placeholder="E-mail" required="required" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <div class="form-group">
                                                    <textarea class="form-control" name="message"
                                                        placeholder="Your Message" required="required"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <button class="btn btn-primary" type="submit"
                                                    [disabled]="!Contact.FormsPreeEmail">Send</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card-body">
                                    <p class="mb-0"><strong>Address </strong></p>
                                    <p class="pb-2">{{Contact.Address}}</p>
                                    <p class="mb-0"><strong>Phone</strong></p>
                                    <p class="pb-2">
                                        <ng-container *ngFor="let phone of Contact.Phones; index as i;">
                                            <span>{{phone}}</span>
                                            <span *ngIf="i < Contact.Phones.length - 1">,&nbsp;</span>
                                        </ng-container>
                                    </p>
                                    <p class="mb-0"><strong>Email</strong></p>
                                    <p>
                                        <ng-container *ngFor="let email of Contact.Emails; index as i;">
                                            <span>{{email}}</span>
                                            <span *ngIf="i < Contact.Emails.length - 1">,&nbsp;</span>
                                        </ng-container>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</agm-map>
