// src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '@services/data.service';
import { BasicInformationModel } from '@shared/models/basic.model';

@Component({
    selector: 'app-footer',
    templateUrl: './footer.component.html'
})
export class FooterComponent implements OnInit {
    private _basicInfo: BasicInformationModel;

    constructor(private _dataService: DataService) {

    }

    ngOnInit(): void {
        this._basicInfo = this._dataService.GetBasicInformation();
    }

    get BasicInformation(): BasicInformationModel {
        return this._basicInfo;
    }

}
<footer class="footer">
    <div class="container text-center">
        <a class="cc-facebook btn btn-link" href="#"><i class="fa fa-facebook fa-2x " aria-hidden="true"></i></a>
        <a class="cc-twitter btn btn-link " href="#"><i class="fa fa-twitter fa-2x " aria-hidden="true"></i></a>
        <a class="cc-google-plus btn btn-link" href="#"><i class="fa fa-google-plus fa-2x" aria-hidden="true"></i></a>
        <a class="cc-instagram btn btn-link" href="#"><i class="fa fa-instagram fa-2x " aria-hidden="true"></i></a>
    </div>
    <div class="h4 title text-center">{{BasicInformation.Name}}</div>
    <div class="text-center text-muted">
        <p>Copyright &copy; 2019 {{BasicInformation.Name}}. All rights reserved.
        <br>Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
    </div>
</footer>

// src/components/Footer.tsx
import { Component } from "react";
import { FULL_NAME } from "../util/constants";

export class Footer extends Component {

    render() {
        return <>
            <footer className="pt-4 pb-4 text-muted text-center d-print-none">
                <div className="container">
                    <div className="my-3">
                        <div className="h4">{FULL_NAME}</div>
                        <div className="footer-nav">
                            <nav role="navigation">
                                <ul className="nav justify-content-center">
                                    <li className="nav-item">
                                        <a className="nav-link" href="https://twitter.com/templateflip" title="Twitter">
                                            <i className="fab fa-twitter"></i>
                                            <span className="menu-title sr-only">Twitter</span>
                                        </a>
                                    </li>
                                    <li className="nav-item">
                                        <a className="nav-link" href="https://www.facebook.com/templateflip" title="Facebook">
                                            <i className="fab fa-facebook"></i>
                                            <span className="menu-title sr-only">Facebook</span>
                                        </a>
                                    </li>
                                    <li className="nav-item">
                                        <a className="nav-link" href="https://www.instagram.com/templateflip" title="Instagram">
                                            <i className="fab fa-instagram"></i>
                                            <span className="menu-title sr-only">Instagram</span>
                                        </a>
                                    </li>
                                    <li className="nav-item">
                                        <a className="nav-link" href="https://github.com/templateflip" title="Github">
                                            <i className="fab fa-github"></i>
                                            <span className="menu-title sr-only">Github</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div className="text-small">
                        <div className="mb-1">&copy; {FULL_NAME}. All rights reserved.</div>
                        <div>Design - <a href="https://templateflip.com/" target="_blank" rel="noreferrer">TemplateFlip</a></div>
                    </div>
                </div>
            </footer>
        </>;
    }
}
