// src/app/content/skills/skills.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-skills',
    templateUrl: './skills.component.html'
})
export class SkillsComponent {

}
<div class="container">
    <div class="h4 text-center mb-4 title">Professional Skills</div>
    <div class="card" data-aos="fade-up" data-aos-anchor-placement="top-bottom">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6" *ngFor="let skill of Skills.ProfessionalSkills;">
                    <div class="progress-container progress-primary">
                        <span class="progress-badge">{{skill.First}}</span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-primary" data-aos="progress-full" data-aos-offset="10"
                                data-aos-duration="2000" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                                aria-valuemax="100" [style.width.%]="skill.Second"></div>
                            <span class="progress-value" style="display: none;">{{skill.Second}}%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// src/components/Skills.tsx
import { Component } from "react";

export class Skills extends Component {

    render() {
        return <>
            <div className="skills-section px-3 px-lg-4">
                <h2 className="h3 mb-3">Professional Skills</h2>
                <div className="row">
                    <div className="col-md-6">
                        <div className="mb-2"><span>HTML</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-primary" role="progressbar" data-aos="zoom-in-right" data-aos-delay={100}
                                    data-aos-anchor=".skills-section" style={{ width: "90%" }} aria-valuenow={90} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                        <div className="mb-2"><span>CSS</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-primary" role="progressbar" data-aos="zoom-in-right" data-aos-delay={200}
                                    data-aos-anchor=".skills-section" style={{ width: "85%" }} aria-valuenow={85} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                        <div className="mb-2"><span>JavaScript</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-primary" role="progressbar" data-aos="zoom-in-right" data-aos-delay={300}
                                    data-aos-anchor=".skills-section" style={{ width: "75%" }} aria-valuenow={75} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-6">
                        <div className="mb-2"><span>Adobe Photoshop</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-success" role="progressbar" data-aos="zoom-in-right" data-aos-delay={400}
                                    data-aos-anchor=".skills-section" style={{ width: "80%" }} aria-valuenow={90} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                        <div className="mb-2"><span>Sketch</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-success" role="progressbar" data-aos="zoom-in-right" data-aos-delay={500}
                                    data-aos-anchor=".skills-section" style={{ width: "85%" }} aria-valuenow={85} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                        <div className="mb-2"><span>Adobe XD</span>
                            <div className="progress my-1">
                                <div className="progress-bar bg-success" role="progressbar" data-aos="zoom-in-right" data-aos-delay={600}
                                    data-aos-anchor=".skills-section" style={{ width: "75%" }} aria-valuenow={75} aria-valuemin={0}
                                    aria-valuemax={100}></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>;
    }
}
